name: test-environment-v5
channels:
- conda-forge
dependencies:
- python==3.12
- pip>=22.1.2
- numpy>=2.0.0
- scipy>=1.9
- matplotlib>=3.9
- imagemagick>=7.1.0_36
- mpmath>=1.2.1
- pytest>=7.1.2
- nbmake>=1.3.4
- jupytext>=1.13.8
- jupyter>=1.0.0
- ipykernel>=6.17.1  # 6.18.0 was yanked but is still present on conda-forge
